// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_VISUALIZER_SLAMD_FLATB_H_
#define FLATBUFFERS_GENERATED_VISUALIZER_SLAMD_FLATB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace slamd {
namespace flatb {

struct Tree;
struct TreeBuilder;

struct View;
struct ViewBuilder;

struct VizFullState;
struct VizFullStateBuilder;

enum TreeType : int8_t {
  TreeType_NONE = 0,
  TreeType_CANVAS = 1,
  TreeType_SCENE = 2,
  TreeType_MIN = TreeType_NONE,
  TreeType_MAX = TreeType_SCENE
};

inline const TreeType (&EnumValuesTreeType())[3] {
  static const TreeType values[] = {
    TreeType_NONE,
    TreeType_CANVAS,
    TreeType_SCENE
  };
  return values;
}

inline const char * const *EnumNamesTreeType() {
  static const char * const names[4] = {
    "NONE",
    "CANVAS",
    "SCENE",
    nullptr
  };
  return names;
}

inline const char *EnumNameTreeType(TreeType e) {
  if (::flatbuffers::IsOutRange(e, TreeType_NONE, TreeType_SCENE)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTreeType()[index];
}

struct Tree FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TreeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ID = 4,
    VT_TREE_TYPE = 6
  };
  uint64_t id() const {
    return GetField<uint64_t>(VT_ID, 0);
  }
  slamd::flatb::TreeType tree_type() const {
    return static_cast<slamd::flatb::TreeType>(GetField<int8_t>(VT_TREE_TYPE, 0));
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ID, 8) &&
           VerifyField<int8_t>(verifier, VT_TREE_TYPE, 1) &&
           verifier.EndTable();
  }
};

struct TreeBuilder {
  typedef Tree Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_id(uint64_t id) {
    fbb_.AddElement<uint64_t>(Tree::VT_ID, id, 0);
  }
  void add_tree_type(slamd::flatb::TreeType tree_type) {
    fbb_.AddElement<int8_t>(Tree::VT_TREE_TYPE, static_cast<int8_t>(tree_type), 0);
  }
  explicit TreeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Tree> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Tree>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Tree> CreateTree(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t id = 0,
    slamd::flatb::TreeType tree_type = slamd::flatb::TreeType_NONE) {
  TreeBuilder builder_(_fbb);
  builder_.add_id(id);
  builder_.add_tree_type(tree_type);
  return builder_.Finish();
}

struct View FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ViewBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_TREE_ID = 6
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  uint64_t tree_id() const {
    return GetField<uint64_t>(VT_TREE_ID, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<uint64_t>(verifier, VT_TREE_ID, 8) &&
           verifier.EndTable();
  }
};

struct ViewBuilder {
  typedef View Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(View::VT_NAME, name);
  }
  void add_tree_id(uint64_t tree_id) {
    fbb_.AddElement<uint64_t>(View::VT_TREE_ID, tree_id, 0);
  }
  explicit ViewBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<View> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<View>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<View> CreateView(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    uint64_t tree_id = 0) {
  ViewBuilder builder_(_fbb);
  builder_.add_tree_id(tree_id);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<View> CreateViewDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    uint64_t tree_id = 0) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  return slamd::flatb::CreateView(
      _fbb,
      name__,
      tree_id);
}

struct VizFullState FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef VizFullStateBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_NAME = 4,
    VT_VIEWS = 6,
    VT_TREES = 8
  };
  const ::flatbuffers::String *name() const {
    return GetPointer<const ::flatbuffers::String *>(VT_NAME);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<slamd::flatb::View>> *views() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<slamd::flatb::View>> *>(VT_VIEWS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<slamd::flatb::Tree>> *trees() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<slamd::flatb::Tree>> *>(VT_TREES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyOffset(verifier, VT_VIEWS) &&
           verifier.VerifyVector(views()) &&
           verifier.VerifyVectorOfTables(views()) &&
           VerifyOffset(verifier, VT_TREES) &&
           verifier.VerifyVector(trees()) &&
           verifier.VerifyVectorOfTables(trees()) &&
           verifier.EndTable();
  }
};

struct VizFullStateBuilder {
  typedef VizFullState Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_name(::flatbuffers::Offset<::flatbuffers::String> name) {
    fbb_.AddOffset(VizFullState::VT_NAME, name);
  }
  void add_views(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slamd::flatb::View>>> views) {
    fbb_.AddOffset(VizFullState::VT_VIEWS, views);
  }
  void add_trees(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slamd::flatb::Tree>>> trees) {
    fbb_.AddOffset(VizFullState::VT_TREES, trees);
  }
  explicit VizFullStateBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<VizFullState> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<VizFullState>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<VizFullState> CreateVizFullState(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> name = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slamd::flatb::View>>> views = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<slamd::flatb::Tree>>> trees = 0) {
  VizFullStateBuilder builder_(_fbb);
  builder_.add_trees(trees);
  builder_.add_views(views);
  builder_.add_name(name);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<VizFullState> CreateVizFullStateDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *name = nullptr,
    const std::vector<::flatbuffers::Offset<slamd::flatb::View>> *views = nullptr,
    const std::vector<::flatbuffers::Offset<slamd::flatb::Tree>> *trees = nullptr) {
  auto name__ = name ? _fbb.CreateString(name) : 0;
  auto views__ = views ? _fbb.CreateVector<::flatbuffers::Offset<slamd::flatb::View>>(*views) : 0;
  auto trees__ = trees ? _fbb.CreateVector<::flatbuffers::Offset<slamd::flatb::Tree>>(*trees) : 0;
  return slamd::flatb::CreateVizFullState(
      _fbb,
      name__,
      views__,
      trees__);
}

}  // namespace flatb
}  // namespace slamd

#endif  // FLATBUFFERS_GENERATED_VISUALIZER_SLAMD_FLATB_H_
