// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_GEOMETRY_SLAMD_FLATB_H_
#define FLATBUFFERS_GENERATED_GEOMETRY_SLAMD_FLATB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

#include "gmath_generated.h"

namespace slamd {
namespace flatb {

struct Triad;
struct TriadBuilder;

struct Circles2D;
struct Circles2DBuilder;

struct Geometry;
struct GeometryBuilder;

enum GeometryUnion : uint8_t {
  GeometryUnion_NONE = 0,
  GeometryUnion_triad = 1,
  GeometryUnion_circles_2d = 2,
  GeometryUnion_MIN = GeometryUnion_NONE,
  GeometryUnion_MAX = GeometryUnion_circles_2d
};

inline const GeometryUnion (&EnumValuesGeometryUnion())[3] {
  static const GeometryUnion values[] = {
    GeometryUnion_NONE,
    GeometryUnion_triad,
    GeometryUnion_circles_2d
  };
  return values;
}

inline const char * const *EnumNamesGeometryUnion() {
  static const char * const names[4] = {
    "NONE",
    "triad",
    "circles_2d",
    nullptr
  };
  return names;
}

inline const char *EnumNameGeometryUnion(GeometryUnion e) {
  if (::flatbuffers::IsOutRange(e, GeometryUnion_NONE, GeometryUnion_circles_2d)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesGeometryUnion()[index];
}

template<typename T> struct GeometryUnionTraits {
  static const GeometryUnion enum_value = GeometryUnion_NONE;
};

template<> struct GeometryUnionTraits<slamd::flatb::Triad> {
  static const GeometryUnion enum_value = GeometryUnion_triad;
};

template<> struct GeometryUnionTraits<slamd::flatb::Circles2D> {
  static const GeometryUnion enum_value = GeometryUnion_circles_2d;
};

bool VerifyGeometryUnion(::flatbuffers::Verifier &verifier, const void *obj, GeometryUnion type);
bool VerifyGeometryUnionVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types);

struct Triad FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TriadBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_SCALE = 4,
    VT_THICKNESS = 6
  };
  float scale() const {
    return GetField<float>(VT_SCALE, 0.0f);
  }
  float thickness() const {
    return GetField<float>(VT_THICKNESS, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<float>(verifier, VT_SCALE, 4) &&
           VerifyField<float>(verifier, VT_THICKNESS, 4) &&
           verifier.EndTable();
  }
};

struct TriadBuilder {
  typedef Triad Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_scale(float scale) {
    fbb_.AddElement<float>(Triad::VT_SCALE, scale, 0.0f);
  }
  void add_thickness(float thickness) {
    fbb_.AddElement<float>(Triad::VT_THICKNESS, thickness, 0.0f);
  }
  explicit TriadBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Triad> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Triad>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Triad> CreateTriad(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    float scale = 0.0f,
    float thickness = 0.0f) {
  TriadBuilder builder_(_fbb);
  builder_.add_thickness(thickness);
  builder_.add_scale(scale);
  return builder_.Finish();
}

struct Circles2D FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef Circles2DBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POSITIONS = 4,
    VT_COLORS = 6,
    VT_RADII = 8,
    VT_THICKNESS = 10
  };
  const ::flatbuffers::Vector<const slamd::flatb::Vec2 *> *positions() const {
    return GetPointer<const ::flatbuffers::Vector<const slamd::flatb::Vec2 *> *>(VT_POSITIONS);
  }
  const ::flatbuffers::Vector<const slamd::flatb::Vec3 *> *colors() const {
    return GetPointer<const ::flatbuffers::Vector<const slamd::flatb::Vec3 *> *>(VT_COLORS);
  }
  const ::flatbuffers::Vector<float> *radii() const {
    return GetPointer<const ::flatbuffers::Vector<float> *>(VT_RADII);
  }
  float thickness() const {
    return GetField<float>(VT_THICKNESS, 0.0f);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_POSITIONS) &&
           verifier.VerifyVector(positions()) &&
           VerifyOffset(verifier, VT_COLORS) &&
           verifier.VerifyVector(colors()) &&
           VerifyOffset(verifier, VT_RADII) &&
           verifier.VerifyVector(radii()) &&
           VerifyField<float>(verifier, VT_THICKNESS, 4) &&
           verifier.EndTable();
  }
};

struct Circles2DBuilder {
  typedef Circles2D Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_positions(::flatbuffers::Offset<::flatbuffers::Vector<const slamd::flatb::Vec2 *>> positions) {
    fbb_.AddOffset(Circles2D::VT_POSITIONS, positions);
  }
  void add_colors(::flatbuffers::Offset<::flatbuffers::Vector<const slamd::flatb::Vec3 *>> colors) {
    fbb_.AddOffset(Circles2D::VT_COLORS, colors);
  }
  void add_radii(::flatbuffers::Offset<::flatbuffers::Vector<float>> radii) {
    fbb_.AddOffset(Circles2D::VT_RADII, radii);
  }
  void add_thickness(float thickness) {
    fbb_.AddElement<float>(Circles2D::VT_THICKNESS, thickness, 0.0f);
  }
  explicit Circles2DBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Circles2D> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Circles2D>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Circles2D> CreateCircles2D(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<const slamd::flatb::Vec2 *>> positions = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const slamd::flatb::Vec3 *>> colors = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<float>> radii = 0,
    float thickness = 0.0f) {
  Circles2DBuilder builder_(_fbb);
  builder_.add_thickness(thickness);
  builder_.add_radii(radii);
  builder_.add_colors(colors);
  builder_.add_positions(positions);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Circles2D> CreateCircles2DDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<slamd::flatb::Vec2> *positions = nullptr,
    const std::vector<slamd::flatb::Vec3> *colors = nullptr,
    const std::vector<float> *radii = nullptr,
    float thickness = 0.0f) {
  auto positions__ = positions ? _fbb.CreateVectorOfStructs<slamd::flatb::Vec2>(*positions) : 0;
  auto colors__ = colors ? _fbb.CreateVectorOfStructs<slamd::flatb::Vec3>(*colors) : 0;
  auto radii__ = radii ? _fbb.CreateVector<float>(*radii) : 0;
  return slamd::flatb::CreateCircles2D(
      _fbb,
      positions__,
      colors__,
      radii__,
      thickness);
}

struct Geometry FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef GeometryBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_GEOMETRY_TYPE = 4,
    VT_GEOMETRY = 6
  };
  slamd::flatb::GeometryUnion geometry_type() const {
    return static_cast<slamd::flatb::GeometryUnion>(GetField<uint8_t>(VT_GEOMETRY_TYPE, 0));
  }
  const void *geometry() const {
    return GetPointer<const void *>(VT_GEOMETRY);
  }
  template<typename T> const T *geometry_as() const;
  const slamd::flatb::Triad *geometry_as_triad() const {
    return geometry_type() == slamd::flatb::GeometryUnion_triad ? static_cast<const slamd::flatb::Triad *>(geometry()) : nullptr;
  }
  const slamd::flatb::Circles2D *geometry_as_circles_2d() const {
    return geometry_type() == slamd::flatb::GeometryUnion_circles_2d ? static_cast<const slamd::flatb::Circles2D *>(geometry()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint8_t>(verifier, VT_GEOMETRY_TYPE, 1) &&
           VerifyOffset(verifier, VT_GEOMETRY) &&
           VerifyGeometryUnion(verifier, geometry(), geometry_type()) &&
           verifier.EndTable();
  }
};

template<> inline const slamd::flatb::Triad *Geometry::geometry_as<slamd::flatb::Triad>() const {
  return geometry_as_triad();
}

template<> inline const slamd::flatb::Circles2D *Geometry::geometry_as<slamd::flatb::Circles2D>() const {
  return geometry_as_circles_2d();
}

struct GeometryBuilder {
  typedef Geometry Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_geometry_type(slamd::flatb::GeometryUnion geometry_type) {
    fbb_.AddElement<uint8_t>(Geometry::VT_GEOMETRY_TYPE, static_cast<uint8_t>(geometry_type), 0);
  }
  void add_geometry(::flatbuffers::Offset<void> geometry) {
    fbb_.AddOffset(Geometry::VT_GEOMETRY, geometry);
  }
  explicit GeometryBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Geometry> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Geometry>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Geometry> CreateGeometry(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    slamd::flatb::GeometryUnion geometry_type = slamd::flatb::GeometryUnion_NONE,
    ::flatbuffers::Offset<void> geometry = 0) {
  GeometryBuilder builder_(_fbb);
  builder_.add_geometry(geometry);
  builder_.add_geometry_type(geometry_type);
  return builder_.Finish();
}

inline bool VerifyGeometryUnion(::flatbuffers::Verifier &verifier, const void *obj, GeometryUnion type) {
  switch (type) {
    case GeometryUnion_NONE: {
      return true;
    }
    case GeometryUnion_triad: {
      auto ptr = reinterpret_cast<const slamd::flatb::Triad *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case GeometryUnion_circles_2d: {
      auto ptr = reinterpret_cast<const slamd::flatb::Circles2D *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyGeometryUnionVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<uint8_t> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyGeometryUnion(
        verifier,  values->Get(i), types->GetEnum<GeometryUnion>(i))) {
      return false;
    }
  }
  return true;
}

}  // namespace flatb
}  // namespace slamd

#endif  // FLATBUFFERS_GENERATED_GEOMETRY_SLAMD_FLATB_H_
