// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PRIMITIVES_SLAMD_FLATB_H_
#define FLATBUFFERS_GENERATED_PRIMITIVES_SLAMD_FLATB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 2 &&
              FLATBUFFERS_VERSION_REVISION == 10,
             "Non-compatible flatbuffers version included");

namespace slamd {
namespace flatb {

struct Vec2;

struct Vec3;

struct Vec4;

struct Mat3;

struct Mat4;

struct ImageData;
struct ImageDataBuilder;

struct MeshData;
struct MeshDataBuilder;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec2 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;

 public:
  Vec2()
      : x_(0),
        y_(0) {
  }
  Vec2(float _x, float _y)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
};
FLATBUFFERS_STRUCT_END(Vec2, 8);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3()
      : x_(0),
        y_(0),
        z_(0) {
  }
  Vec3(float _x, float _y, float _z)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec4 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;
  float w_;

 public:
  Vec4()
      : x_(0),
        y_(0),
        z_(0),
        w_(0) {
  }
  Vec4(float _x, float _y, float _z, float _w)
      : x_(::flatbuffers::EndianScalar(_x)),
        y_(::flatbuffers::EndianScalar(_y)),
        z_(::flatbuffers::EndianScalar(_z)),
        w_(::flatbuffers::EndianScalar(_w)) {
  }
  float x() const {
    return ::flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return ::flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return ::flatbuffers::EndianScalar(z_);
  }
  float w() const {
    return ::flatbuffers::EndianScalar(w_);
  }
};
FLATBUFFERS_STRUCT_END(Vec4, 16);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Mat3 FLATBUFFERS_FINAL_CLASS {
 private:
  float data_[9];

 public:
  Mat3()
      : data_() {
  }
  Mat3(::flatbuffers::span<const float, 9> _data) {
    ::flatbuffers::CastToArray(data_).CopyFromSpan(_data);
  }
  const ::flatbuffers::Array<float, 9> *data() const {
    return &::flatbuffers::CastToArray(data_);
  }
};
FLATBUFFERS_STRUCT_END(Mat3, 36);

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Mat4 FLATBUFFERS_FINAL_CLASS {
 private:
  float data_[16];

 public:
  Mat4()
      : data_() {
  }
  Mat4(::flatbuffers::span<const float, 16> _data) {
    ::flatbuffers::CastToArray(data_).CopyFromSpan(_data);
  }
  const ::flatbuffers::Array<float, 16> *data() const {
    return &::flatbuffers::CastToArray(data_);
  }
};
FLATBUFFERS_STRUCT_END(Mat4, 64);

struct ImageData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ImageDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_WIDTH = 4,
    VT_HEIGHT = 6,
    VT_PIXELS = 8
  };
  uint32_t width() const {
    return GetField<uint32_t>(VT_WIDTH, 0);
  }
  uint32_t height() const {
    return GetField<uint32_t>(VT_HEIGHT, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *pixels() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_PIXELS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_WIDTH, 4) &&
           VerifyField<uint32_t>(verifier, VT_HEIGHT, 4) &&
           VerifyOffset(verifier, VT_PIXELS) &&
           verifier.VerifyVector(pixels()) &&
           verifier.EndTable();
  }
};

struct ImageDataBuilder {
  typedef ImageData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_width(uint32_t width) {
    fbb_.AddElement<uint32_t>(ImageData::VT_WIDTH, width, 0);
  }
  void add_height(uint32_t height) {
    fbb_.AddElement<uint32_t>(ImageData::VT_HEIGHT, height, 0);
  }
  void add_pixels(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> pixels) {
    fbb_.AddOffset(ImageData::VT_PIXELS, pixels);
  }
  explicit ImageDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ImageData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ImageData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ImageData> CreateImageData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t width = 0,
    uint32_t height = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> pixels = 0) {
  ImageDataBuilder builder_(_fbb);
  builder_.add_pixels(pixels);
  builder_.add_height(height);
  builder_.add_width(width);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<ImageData> CreateImageDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t width = 0,
    uint32_t height = 0,
    const std::vector<uint8_t> *pixels = nullptr) {
  auto pixels__ = pixels ? _fbb.CreateVector<uint8_t>(*pixels) : 0;
  return slamd::flatb::CreateImageData(
      _fbb,
      width,
      height,
      pixels__);
}

struct MeshData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MeshDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_POSITIONS = 4,
    VT_COLORS = 6,
    VT_TRIANGLE_INDICES = 8,
    VT_NORMALS = 10
  };
  const ::flatbuffers::Vector<const slamd::flatb::Vec3 *> *positions() const {
    return GetPointer<const ::flatbuffers::Vector<const slamd::flatb::Vec3 *> *>(VT_POSITIONS);
  }
  const ::flatbuffers::Vector<const slamd::flatb::Vec3 *> *colors() const {
    return GetPointer<const ::flatbuffers::Vector<const slamd::flatb::Vec3 *> *>(VT_COLORS);
  }
  const ::flatbuffers::Vector<uint32_t> *triangle_indices() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_TRIANGLE_INDICES);
  }
  const ::flatbuffers::Vector<const slamd::flatb::Vec3 *> *normals() const {
    return GetPointer<const ::flatbuffers::Vector<const slamd::flatb::Vec3 *> *>(VT_NORMALS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_POSITIONS) &&
           verifier.VerifyVector(positions()) &&
           VerifyOffset(verifier, VT_COLORS) &&
           verifier.VerifyVector(colors()) &&
           VerifyOffset(verifier, VT_TRIANGLE_INDICES) &&
           verifier.VerifyVector(triangle_indices()) &&
           VerifyOffset(verifier, VT_NORMALS) &&
           verifier.VerifyVector(normals()) &&
           verifier.EndTable();
  }
};

struct MeshDataBuilder {
  typedef MeshData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_positions(::flatbuffers::Offset<::flatbuffers::Vector<const slamd::flatb::Vec3 *>> positions) {
    fbb_.AddOffset(MeshData::VT_POSITIONS, positions);
  }
  void add_colors(::flatbuffers::Offset<::flatbuffers::Vector<const slamd::flatb::Vec3 *>> colors) {
    fbb_.AddOffset(MeshData::VT_COLORS, colors);
  }
  void add_triangle_indices(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> triangle_indices) {
    fbb_.AddOffset(MeshData::VT_TRIANGLE_INDICES, triangle_indices);
  }
  void add_normals(::flatbuffers::Offset<::flatbuffers::Vector<const slamd::flatb::Vec3 *>> normals) {
    fbb_.AddOffset(MeshData::VT_NORMALS, normals);
  }
  explicit MeshDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MeshData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MeshData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MeshData> CreateMeshData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<const slamd::flatb::Vec3 *>> positions = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const slamd::flatb::Vec3 *>> colors = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> triangle_indices = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<const slamd::flatb::Vec3 *>> normals = 0) {
  MeshDataBuilder builder_(_fbb);
  builder_.add_normals(normals);
  builder_.add_triangle_indices(triangle_indices);
  builder_.add_colors(colors);
  builder_.add_positions(positions);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MeshData> CreateMeshDataDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<slamd::flatb::Vec3> *positions = nullptr,
    const std::vector<slamd::flatb::Vec3> *colors = nullptr,
    const std::vector<uint32_t> *triangle_indices = nullptr,
    const std::vector<slamd::flatb::Vec3> *normals = nullptr) {
  auto positions__ = positions ? _fbb.CreateVectorOfStructs<slamd::flatb::Vec3>(*positions) : 0;
  auto colors__ = colors ? _fbb.CreateVectorOfStructs<slamd::flatb::Vec3>(*colors) : 0;
  auto triangle_indices__ = triangle_indices ? _fbb.CreateVector<uint32_t>(*triangle_indices) : 0;
  auto normals__ = normals ? _fbb.CreateVectorOfStructs<slamd::flatb::Vec3>(*normals) : 0;
  return slamd::flatb::CreateMeshData(
      _fbb,
      positions__,
      colors__,
      triangle_indices__,
      normals__);
}

}  // namespace flatb
}  // namespace slamd

#endif  // FLATBUFFERS_GENERATED_PRIMITIVES_SLAMD_FLATB_H_
