name: Upload Python Package to PyPI when a Release is Created

# on:
#   release:
#     types: [created]

on: [push]

jobs:
  build-linux:
    name: Build wheels on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Copy stuff
        run: |
          rm -rf python_bindings/vendored_deps
          rm -rf python_bindings/slamd_src
          rm -rf python_bindings/README.md

          cp -r vendored_deps python_bindings/vendored_deps
          cp -r slamd python_bindings/slamd_src
          cp README.md python_bindings/README.md

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel

      - name: Build wheels with cibuildwheel
        env:
          CIBW_ARCHS_LINUX: 'x86_64'
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_BEFORE_ALL_LINUX: |
            yum install -y epel-release && \
            yum install -y \
              glfw-devel \
              libX11-devel \
              libXcursor-devel \
              libXrandr-devel \
              libXinerama-devel \
              libXi-devel \
              wayland-devel \
              mesa-libEGL-devel \
              mesa-libGLES-devel \
              SDL2-devel \
              qt5-qtbase-devel \
              gtk3-devel
        run: |
          cd python_bindings
          cibuildwheel --output-dir dist

      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-linux
          path: python_bindings/dist

  build-macos:
    name: Build wheels on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Copy stuff
        run: |
          rm -rf python_bindings/vendored_deps
          rm -rf python_bindings/slamd_src
          rm -rf python_bindings/README.md

          cp -r vendored_deps python_bindings/vendored_deps
          cp -r slamd python_bindings/slamd_src
          cp README.md python_bindings/README.md

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel

      - name: Build wheels with cibuildwheel
        run: |
          cd python_bindings
          cibuildwheel --output-dir dist

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-macos
          path: python_bindings/dist

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [build-linux, build-macos] # 🔥 waits for both builds
    environment:
      name: pypi
    permissions:
      id-token: write
    steps:
      - name: Download Linux wheels
        uses: actions/download-artifact@v4
        with:
          name: dist-linux
          path: dist

      - name: Download macOS wheels
        uses: actions/download-artifact@v4
        with:
          name: dist-macos
          path: dist

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist
