name: Upload Python Package to PyPI when a Release is Created

# on:
# release:
#   types: [created]
on:
  push:
    branches:
      - main # or whatever branch you're pushing to

jobs:
  pypi-publish:
    name: Publish release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Copy stuff
        run: |
          rm -rf python_bindings/vendored_deps
          rm -rf python_bindings/slamd_src
          rm -rf python_bindings/README.md

          cp -r vendored_deps python_bindings/vendored_deps
          cp -r slamd python_bindings/slamd_src
          cp README.md python_bindings/README.md

      # - name: Set up Python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.11'

      # - name: Install build deps
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install cibuildwheel
      - name: Build custom Docker image
        run: docker build -t gcc13-wheel -f python_bindings/build_images/manylinux/Dockerfile .

      - name: Build wheels with cibuildwheel
        env:
          CIBW_MANYLINUX_X86_64_IMAGE: gcc13-wheel
          CIBW_BEFORE_ALL: |
            yum install -y epel-release && \
            yum install -y \
              glfw-devel \
              libX11-devel \
              libXcursor-devel \
              libXrandr-devel \
              libXinerama-devel \
              libXi-devel \
              wayland-devel \
              mesa-libEGL-devel \
              mesa-libGLES-devel \
              SDL2-devel \
              qt5-qtbase-devel \
              gtk3-devel

        run: |
          cd python_bindings
          cibuildwheel --output-dir dist

      # - name: Install build deps
      #   run: |
      #     python -m pip install --upgrade pip
      #     pip install build

      # - name: Build package
      #   run: |
      #     python -m build python_bindings

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: python_bindings/dist
