name: Build python wheels

on: [pull_request]

jobs:
  build-wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Copy stuff
        run: |
          rm -rf python_bindings/vendored_deps
          rm -rf python_bindings/slamd_src
          rm -rf python_bindings/README.md

          cp -r vendored_deps python_bindings/vendored_deps
          cp -r slamd python_bindings/slamd_src
          cp README.md python_bindings/README.md

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build deps
        run: |
          python -m pip install --upgrade pip
          pip install cibuildwheel

      - name: Build wheels with cibuildwheel
        env:
          CIBW_ARCHS_LINUX: 'x86_64'
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_ENVIRONMENT_MACOS: 'MACOSX_DEPLOYMENT_TARGET=13.3'
          CIBW_BEFORE_ALL_LINUX: |
            yum install -y epel-release && \
            yum install -y \
              glfw-devel \
              libX11-devel \
              libXcursor-devel \
              libXrandr-devel \
              libXinerama-devel \
              libXi-devel \
              wayland-devel \
              mesa-libEGL-devel \
              mesa-libGLES-devel \
              SDL2-devel \
              qt5-qtbase-devel \
              gtk3-devel
        run: |
          cd python_bindings
          cibuildwheel --output-dir dist
